CC = g++

FLAGS = -std=c++14 -Wall -g

hw04: hw04.cpp 
    $(CC)  hw04.cpp -o employee.h programmer.h software.h hw04

tar:
	tar cf hw04.tar hw04.scr Makefile hw04.cpp date.h employee.h programmer.h software.h
