CC = g++

FLAGS = -std=c++14 -Wall -g

hw03: hw03.cpp 
    $(CC)  hw03.cpp -o employee.h programmer.h software.h hw03

tar:
	tar cf hw03.tar hw03.scr Makefile hw03.cpp date.h employee.h programmer.h software.h
